language: node_js

node_js:
  - 12.9.0

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: 'dist/'
  on:
    branch: master
  verbose: true